### ISSUE TITLE
Establish DynamoDB Connection

### ISSUE THREAD

**Issue by AnthonySMyers** [nnguyen682/CECS491ATeam4#37]
We will connect our Lambda Function instance to a DynamoDB table for user data storage.

**Comment by AnthonySMyers** [comment]
We have added code to the Good Vibes Lambda Function that establishes a connection to a DynamoDB table. The setup followed the guidelines that I wrote in the text file.

[Steps for DynamoDB.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a66619da7ba990013f053dc/125516c66e82c728ace21e0d46db809f3391c3af80fbff67bd53f199266205316546b3397f8fe62bab0021435a0e48fd100c0d12fea8812ba6e73c708d0a59edd4390b72d42103eee9dc4be05ce36ade0d97bcae8b4bcae93826e0888f4a371a071181fd4f78.txt)

**Comment by jespinoza17** [comment]
The only issue we may encounter in the future may be which data table the user attributes are stored in. For example, Since me and Nhan have different AWS accounts, we have separate lambda functions and dynamoDB tables. Although the code is exactly the same, the user data will only be stored in the table whose lambda ARN is connected to the developer portal.

**Comment by nnguyen682** [comment]
I added the code in my Lambda with Anthony showings me and it runs successfully on my end.
